### ISSUE TITLE
Mod name is 'FallFest 2020' not 'Dark Dungeons'

### ISSUE THREAD

**Issue by RiAlwayNut69** [Geek202/FallFest2020#13]
![image](https://user-images.githubusercontent.com/76866274/117539330-596c7480-b034-11eb-8c8f-25541e359c0f.png)

**Comment by Tom-The-Geek** [comment]
The mod name as shown in modmenu is `FallFest 2020` because I didn't have a name when I created the mod, so I just named it after the competition.
