### ISSUE TITLE
Skeletons don't spawn with bows

### ISSUE THREAD

**Issue by DaddySpin** [Geek202/FallFest2020#2]
When ever a skeleton spawns from a wave it does not spawn with a bow.
![2020-10-15_10 29 12](https://user-images.githubusercontent.com/34575655/96151654-498f1680-0ed1-11eb-86bf-7e9f6e1cdc78.png)

**Comment by Tom-The-Geek** [comment]
I'll look into why this happens, its probably an issue with how I spawn the mobs in or smth.
