### ISSUE TITLE
Custom Spawner Profiles Don't Seem Work

### ISSUE THREAD

**Issue by mahjerion** [Geek202/FallFest2020#9]
I've double checked the logs, and it registers that I have 17 custom profiles - no errors either. But when I encounter cursed spawners, it's just the standard spawner_room.json that loads.

**Comment by Tom-The-Geek** [comment]
You have to manually change the profile on the spawner with a `/setblock` or `/data merge block` command. The NBT to set is `{Profile:"<profile>"}`. If you want to replace the profile used in dungeon rooms, then you should be able to place your custom profile at the same location as the default within a datapack and it will then be loaded instead.

**Comment by mahjerion** [comment]
Oh nice, thanks. If I add a bunch of "spawner rooms" and set the dungeon_path.json to have different spawner rooms, would I encounter any issues where I'll have multiple spawner rooms? Or does your mod work in a way that it stops upon encountering a room with a cursed spawner?

If it's not clear what I mean, I have two structures: spawner_room.nbt and another_spawner_room.nbt. In the template pool for dungeon_path.json, I've added an additional possibility.
![image](https://user-images.githubusercontent.com/66142256/101717049-9542e400-3a6c-11eb-94c1-50ba3e2b75c0.png)

**Comment by mahjerion** [comment]
Actually just tested it, it works :) thanks!

**Comment by Tom-The-Geek** [comment]
The mod doesn't do any particular checks if a spawner room has already generated, I just do my best biasing the structure pools so that only one spawns.
